### ISSUE TITLE
Add installation instructions to `README.md`

### ISSUE THREAD

**Issue by s-a** [DGH2112/Auto-Save#1]
How to install this extension? I found this page anywhere on your blog http://www.davidghoyle.co.uk/WordPress/?p=1232 but `TL;DR`

**Comment by DGH2112** [comment]
Stephan,
You would need to build the source code from Git. On the web page (
http://www.davidghoyle.co.uk/WordPress/?page_id=918) there is a ZIP file
with most binaries you can download. For instructions on how to compile and
install see the link at the bottom of the page (Compiling and Installing my
experts and wizards… <http://www.davidghoyle.co.uk/WordPress/?p=1232>).

regards
David Hoyle.
"Wheels within wheels in a spiral array, A pattern so grand and complex,
Time after time we lose sight of the way, Our causes can't see their
effects." - Neil Peart, Rush
Website: http://www.davidghoyle.co.uk/WordPress/
